import { defineDb } from "astro:db";

// Generated by scripts/generate-db-config.mjs
import { User, Session, Account, Verification } from './tables.generated';

export default defineDb({
  tables: {
    User,
    Session,
    Account,
    Verification,
  },
});