import { defineDb } from "astro:db";

// Generated by scripts/generate-db-config.mjs
import { User, Post, Comment } from './tables.generated';

export default defineDb({
  tables: {
    User,
    Post,
    Comment,
  },
});